# 安装 clickhouse
- import_tasks: install.yml
  when: 'OP_TYPE == "install"'

# 启动 clickhouse
- import_tasks: start.yml
  when: 'OP_TYPE == "start"'

# 停止 clickhouse
- import_tasks: stop.yml
  when: 'OP_TYPE == "stop"'

# 卸载 clickhouse
- import_tasks: uninstall.yml
  when: 'OP_TYPE == "uninstall"'